# Generated by Django 3.0.8 on 2020-07-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sate',
            new_name='state',
        ),
    ]
